/**
 * PPTX Engine — Create PowerPoint presentations
 * Uses: pptxgenjs (pure JS)
 */

let PptxClass: (new () => import('pptxgenjs').default) | null = null

async function getPptxConstructor() {
  if (!PptxClass) {
    const mod = await import('pptxgenjs')
    // Handle both ESM default export and CJS module.exports
    PptxClass = (mod.default ?? mod) as new () => import('pptxgenjs').default
  }
  return PptxClass
}

export interface SlideContent {
  title?: string
  body?: string
  bullets?: string[]
  notes?: string
}

export interface PptxCreateOptions {
  title?: string
  author?: string
  layout?: 'LAYOUT_16x9' | 'LAYOUT_4x3'
}

/**
 * Create a PPTX from structured slide content
 */
export async function createPptx(
  slides: SlideContent[],
  outputPath: string,
  options: PptxCreateOptions = {}
): Promise<string> {
  const PptxGenJS = await getPptxConstructor()
  const pptx = new PptxGenJS()

  pptx.author = options.author ?? 'Usan'
  pptx.title = options.title ?? 'Presentation'
  pptx.layout = options.layout ?? 'LAYOUT_16x9'

  for (const content of slides) {
    const slide = pptx.addSlide()

    if (content.title) {
      slide.addText(content.title, {
        x: 0.5,
        y: 0.3,
        w: '90%',
        h: 1,
        fontSize: 28,
        bold: true,
        color: '111827',
      })
    }

    if (content.body) {
      slide.addText(content.body, {
        x: 0.5,
        y: 1.5,
        w: '90%',
        h: 4,
        fontSize: 16,
        color: '4b5563',
        lineSpacingMultiple: 1.4,
      })
    }

    if (content.bullets?.length) {
      const bulletText = content.bullets.map((b) => ({
        text: b,
        options: { bullet: true, fontSize: 16, color: '4b5563' as const },
      }))
      slide.addText(bulletText, {
        x: 0.5,
        y: content.title ? 1.5 : 0.5,
        w: '90%',
        h: 4,
        lineSpacingMultiple: 1.6,
      })
    }

    if (content.notes) {
      slide.addNotes(content.notes)
    }
  }

  await pptx.writeFile({ fileName: outputPath })
  return outputPath
}

/**
 * Create a simple title slide + content slides from text
 */
export async function textToPptx(
  title: string,
  sections: { heading: string; content: string }[],
  outputPath: string
): Promise<string> {
  const slides: SlideContent[] = [
    { title, body: `Generated by Usan\n${new Date().toLocaleDateString('ko-KR')}` },
  ]

  for (const section of sections) {
    slides.push({
      title: section.heading,
      body: section.content,
    })
  }

  return createPptx(slides, outputPath, { title })
}
